export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_GAMEBYID = "GET_GAMEBYID";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const GET_GAMEBYNAME = "GET_GAMEBYNAME";
